version: '3'

services:
  #Servidor Web, no caso, o nginx
  webserver:
    build: docker/api
    depends_on:
      - app
    ports:
      - "7777:80"
    volumes:
      - ./:/app
    networks:
      - matematica

  app:
    build: docker/app
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - matematica

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=matematica
    ports:
      - "3309:3306"
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - matematica

#Redes
networks:
  matematica:
    driver: "bridge"

#Volumes
volumes:
  dbdata:
    driver: local
